name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          docker compose build
          docker compose up -d

#      - name: Run tests
#        run: |
#          docker compose exec python poetry run pytest --cov=.

      - name: Clean
        run: docker compose down -v --remove-orphans

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: app/htmlcov
          retention-days: 5